### ISSUE TITLE
How to remove canvas? 

### ISSUE THREAD

**Issue by iancoetzer** [mizrael/Blazorex#4]
When I navigate to another razor page, the canvas onframeready and on resize events are still being invoked from Javascript?

How can I dispose of a canvas to which I have hooked events?

**Comment by iancoetzer** [comment]
from what i can gather, we need a way to remove the item from _contexts in the blazorex.js java script file, since the script iterates all contexts in _contexts collection when frame is resized, animation frame is updated etc.?

**Comment by mizrael** [comment]
hi @iancoetzer would you be able to put up a quick example to repro the issue? thanks!

**Comment by iancoetzer** [comment]
Hi
Here is a sample, I navigate to a razor page, which starts to print in console using the OnFrameReady event. However, when I return to my home page, I want to remove reference to the Canvas from the Blazorex._contexts array so that it no longer emmits Javascript events on resize, animation frame etc. only when I return to that razor page that contains that specific canvas. How do I do that?
![blazorex](https://github.com/mizrael/Blazorex/assets/7976311/260afac6-9592-4098-a802-8f2058577fd5)

**Comment by iancoetzer** [comment]
Another issue related to this is when I return to the razor page that contains the canvas it starts emitting new onframeready events for the *new* canvas, and now in console window you will see that the onframeready event fires twice at the same time, and three times when i return to home and the razor page the third time ...

![blazorex2](https://github.com/mizrael/Blazorex/assets/7976311/bc6c229c-e8ec-4c98-94a1-68d493272c6a)

**Comment by iancoetzer** [comment]
Is there a way to use IDispose to remove the instance of this _canvas.Id from the Blazorex._contexts array?

```@page "/development/resizedemoblazorex"

@implements IDisposable
@inject IJSRuntime JSRuntime

<Blazorex.Canvas
    OnFrameReady="(x)=>OnFrameReady(x)"
    OnCanvasReady="(x)=>OnCanvasReady(x)"
    OnResize="(x)=>OnResize(x)"
></Blazorex.Canvas>

@code{
    Blazorex.CanvasBase _canvas;

    private async Task OnCanvasReady(Blazorex.CanvasBase canvas)
    {
        _canvas = canvas;
        Console.WriteLine(_canvas.Id);
    }

    private void OnFrameReady(float timeStamp)
    {
        // your render logic goes here
        Console.WriteLine(timeStamp);
    }

    private async Task OnResize(Blazorex.Size size)
    {
        Console.WriteLine(size);
    }

    public void Dispose()
    {
        // how can i remove _canvas.Id from the Blazorex._contexts array, 
        // so that it no longer emits javascript functions back to this instance of the client / razor page?
    }
}

**Comment by iancoetzer** [comment]
I do not know how to implement this, but can we request a new method in blazorex.js?
I do not know if this will work or how to implement this, so that we can call this when the parent component / razor page is disposed of?

```
window.Blazorex.removeContext = (contextId) => {
    delete window.Blazorex._contexts[contextId];
};

**Comment by iancoetzer** [comment]
> hi @iancoetzer would you be able to put up a quick example to repro the issue? thanks!
Hi @mizrael please let me know if this change could be made to the blazorex.js and if you reckon it could then be used to call into the javascript to remove a canvas context by id when a razor page is disposed?

Thanks,
Ian

**Comment by iancoetzer** [comment]
First attempt to contribute to a public repo.
Managed to fork your project, build it locally and test it in my local development environment (a simple blazor webassembly project being developed in the vscode IDE).

**Comment by mizrael** [comment]
thank you very much @iancoetzer! I am enjoying some holidays now, I'll make sure to have a look at your PR and keep you posted!
